// Generated by CoffeeScript 1.3.3
(function() {
  var Seq, app, request, should;

  request = require('supertest');

  Seq = require('seq');

  app = require('../server');

  should = require('should');

  describe('POST /horde', function() {
    afterEach(function(done) {
      return request(app).del('/horde').end(done);
    });
    it('responds with 201 on success', function(done) {
      return request(app).post('/horde').send({
        url: 'http://google.com'
      }).expect(201, done);
    });
    it('responds with 412 without url', function(done) {
      return request(app).post('/horde').send({}).expect(412, done);
    });
    it('responds with json', function(done) {
      return request(app).post('/horde').send({
        url: 'http://google.com'
      }).expect('Content-Type', /json/, done);
    });
    it('creates an instance', function(done) {
      return Seq().seq_(function(next) {
        return request(app).post('/horde').send({
          url: 'http://google.com'
        }).expect(201).end(next);
      }).seq_(function(next) {
        return request(app).get('/horde/alive').end(function(err, res) {
          JSON.parse(res.text).tot.should.equal(1);
          return done();
        });
      });
    });
    it('creates an instance returning the new one', function(done) {
      return request(app).post('/horde').send({
        url: 'http://google.com'
      }).expect(201).end(function(err, res) {
        var data;
        data = JSON.parse(res.text);
        should.exist(data.created);
        should.exist(data.created.guid);
        should.exist(data.created.url);
        return done();
      });
    });
    return it('creates an instance returning the horde', function(done) {
      return request(app).post('/horde').send({
        url: 'http://google.com'
      }).expect(201).end(function(err, res) {
        var data;
        data = JSON.parse(res.text);
        should.exist(data.horde);
        data.horde.should.be.an.instanceOf(Array);
        should.exist(data.horde[0].guid);
        should.exist(data.horde[0].url);
        return done();
      });
    });
  });

}).call(this);
