// Generated by CoffeeScript 1.3.3
(function() {
  var Seq, app, request;

  request = require('supertest');

  Seq = require('seq');

  app = require('../server');

  describe('PUT', function() {
    afterEach(function(done) {
      return request(app).del('/horde').end(done);
    });
    return describe('/horde/spells/:spell', function() {
      return it('casts a spell on the horde', function(done) {
        var guid, spell;
        spell = '';
        guid = '';
        return Seq().seq_(function(next) {
          return request(app).post('/horde').send({
            url: 'http://localhost:8000'
          }).end(function(err, res) {
            guid = JSON.parse(res.text).created.guid;
            return next();
          });
        }).seq_(function(next) {
          return request(app).get('/spells/localhost:8000').end(function(err, res) {
            spell = JSON.parse(res.text)[0].name;
            return next();
          });
        }).seq_(function(next) {
          return request(app).put("/horde/" + guid + "/spells/" + spell).end(function(err, res) {
            JSON.parse(res.text).result.should.equal(true);
            return done();
          });
        });
      });
    });
  });

}).call(this);
