// Generated by CoffeeScript 1.3.3
(function() {

  describe('spells', function() {
    var Browser;
    Browser = require('zombie');
    it('could be invoked', function(done) {
      return require('./fixtures/spells/simple')(function(data) {
        data.should.equal('done');
        return done();
      });
    });
    it('could get the title', function(done) {
      return require('./fixtures/spells/open-url')(new Browser, function(data) {
        data.should.equal('Sample site');
        return done();
      });
    });
    return it('could write a custom string in a field', function(done) {
      return require('./fixtures/spells/fill-field')(new Browser, function(data) {
        data.should.equal('sample string');
        return done();
      });
    });
  });

}).call(this);
