// Generated by CoffeeScript 1.3.3
(function() {
  var Seq, app, request, _;

  request = require('supertest');

  Seq = require('seq');

  app = require('../../server');

  _ = require('underscore');

  describe('POST', function() {
    return describe('/spooky', function() {
      var create, n;
      n = 337;
      it('creates n instances', function(done) {
        return create(function() {
          return request(app).get('/horde/alive').end(function(err, res) {
            JSON.parse(res.text).tot.should.equal(n);
            return done();
          });
        });
      });
      return create = function(done) {
        return Seq().seq_(function(next) {
          return request(app).del('/horde').end(function() {
            return next();
          });
        }).seq_(function(next) {
          return request(app).get('/horde/alive').end(function(err, res) {
            JSON.parse(res.text).tot.should.equal(0);
            return next();
          });
        }).seq_(function(next) {
          return _.times(n, function(i) {
            return request(app).post('/horde').send({
              url: 'http://localhost:8000'
            }).expect(201).end(function() {
              console.log("created " + i + "th instance");
              if (i === n - 1) {
                return done();
              }
            });
          });
        });
      };
    });
  });

}).call(this);
