// Generated by CoffeeScript 1.3.3
(function() {
  var Browser, browser, hostname, spellName, url;

  Browser = require('zombie');

  url = 'http://localhost:8000';

  hostname = 'localhost:8000';

  spellName = 'title.js';

  browser = new Browser;

  browser.visit(url, function(error, browser, statusCode, errors) {
    var spell;
    spell = require("../spells/" + hostname + "/" + spellName);
    return spell(browser, function(result, found, expected) {
      return console.log("result is " + result + ", you sent\n" + found + "\nand I expected\n" + expected);
    });
  });

}).call(this);
