// Generated by CoffeeScript 1.3.3
(function() {
  var argv, exec, hostname, spellName, url, wd;

  wd = require('wd');

  exec = require('child_process').exec;

  argv = require('optimist').usage('Usage: $0 -n name').demand('n').argv;

  url = 'http://localhost:8000';

  hostname = 'localhost:8000';

  spellName = argv.n;

  exec('phantomjs --webdriver=9200', function(err, stdout, stderr) {
    var instance;
    instance = wd.promiseRemote('127.0.0.1', 9200);
    return instance.init(function() {
      var spell;
      spell = require("../spells/" + hostname + "/" + spellName);
      return spell(instance, function(success, found, expected) {
        return console.log("result is " + success + ", you sent\n" + found + "\nand I expected\n" + expected);
      });
    });
  });

}).call(this);
